### ISSUE TITLE
glyphicons.png should have a transparent background

### ISSUE THREAD

**Issue by huug** [marcoceppi/bootstrap-glyphicons#1]
The sprite has a white background.

**Comment by marcoceppi** [comment]
I have an update for this that I haven't pushed yet because of some left over artifacts. (not pure white).

**Comment by palodelincak** [comment]
Hello, any progress on this issue?

**Comment by sourcecodes2** [comment]
Here you go, 100% transparent:
![glyphicons-black](https://f.cloud.github.com/assets/202094/94034/9a0f1cb6-663e-11e2-94a7-6d4f910355eb.png)

Will be uploading a white transparent version shortly too :+1: (See other bug report)

**Comment by huug** [comment]
I use icon-font instead, tnx!
